#!/bin/bash

echo "Start installing conky-theme"
cp template conkyrc
echo "Copying conkyrc template"
echo "Calling Coingecko APIs and generating prices.json"
mv conkyrc ~/.conkyrc
echo "Moving conkyrc"
echo "done."
conky
